#!/bin/sh

mvn -f core/pom.xml clean install
mvn -f zxcommons/pom.xml clean install
mvn -f microsha/pom.xml clean package
mvn -f zxspectrum/pom.xml clean package
mvn -f disasm/z80/pom.xml clean package